#!/bin/bash

timer=600
wallpapers_folder="$HOME/Pictures/Wallpapers"

while true; do
	pics=`find "$wallpapers_folder/" -type f | shuf`
	for f in $pics; do
		gsettings set org.gnome.desktop.background picture-uri "file://$(realpath $f)";
		# echo $f `date` > ~/tmp/current_wallpaper.log
		sleep $timer;
	done
done
